"""Initial migration.

Revision ID: 717269f0df73
Revises: 
Create Date: 2024-02-29 10:38:10.447105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717269f0df73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['guid'])

    with op.batch_alter_table('article_queue', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['guid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_queue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
