"""empty message

Revision ID: 907d48321ff0
Revises: 6f7962c96bfd
Create Date: 2024-02-21 09:29:28.888466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907d48321ff0'
down_revision = '6f7962c96bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
